### ISSUE TITLE
add default state manager

### ISSUE THREAD

**Issue by lucafalasco** [accurat/accurapp#17]
Maybe MobX?

**Comment by marcofugaro** [comment]
you don't always need it, I don't need a state manager in my current project

**Comment by markov00** [comment]
less boilerplate is a better boilerplate

**Comment by lucafalasco** [comment]
I don't always need d3 either, would be nice to have it at least as a command line option.. 
I guess for it to be really useful some customization options should be provided, otherwise I don't really need a boilerplate, I can just copy/paste 😏

**Comment by markov00** [comment]
what if we remove d3 and lodash, and we can just use `yarn add sticaz` to add our dependencies?

**Comment by caesarsol** [comment]
or you just `yarn remove sticaz` if you really don't need it...? 😆

**Comment by markov00** [comment]
We keep `d3` and `lodash` and the user will add any other dependencies
