### ISSUE TITLE
SVG Loader

### ISSUE THREAD

**Issue by lucafalasco** [accurat/accurapp#19]
https://github.com/boopathi/react-svg-loader

**Comment by marcofugaro** [comment]
Relevant create-react-app discussions

https://github.com/facebook/create-react-app/pull/3718/files

https://github.com/facebook/create-react-app/pull/3907/files

https://github.com/facebook/create-react-app/issues/3856

https://github.com/smooth-code/svgr/issues/52

**Comment by marcofugaro** [comment]
Closed in #40
