### ISSUE TITLE
🚧 🚨 Interesting ESLint rules and plugins

### ISSUE THREAD

**Issue by caesarsol** [accurat/accurapp#5]
@marcofugaro @lucafalasco @nkint @markov00 

Let's list all the **eslint** related proposals in this issue.

One proposal per post, votes through reactions.

**Comment by caesarsol** [comment]
http://eslint.org/docs/rules/no-implicit-coercion

**Comment by marcofugaro** [comment]
https://github.com/amilajack/eslint-plugin-compat

**Comment by marcofugaro** [comment]
con questo la qualità del codice che scriviamo va alle stelle

https://github.com/evcohen/eslint-plugin-jsx-a11y

**Comment by marcofugaro** [comment]
interessante per i pattern

https://github.com/xjamundx/eslint-plugin-promise

**Comment by nkint** [comment]
http://eslint.org/docs/rules/callback-return

**Comment by nkint** [comment]
http://eslint.org/docs/rules/no-shadow !!!

**Comment by caesarsol** [comment]
http://eslint.org/docs/rules/no-bitwise

**Comment by marcofugaro** [comment]
https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md

**Comment by marcofugaro** [comment]
http://eslint.org/docs/rules/prefer-template

**Comment by marcofugaro** [comment]
https://eslint.org/docs/rules/id-length
(con delle exceptions però)

**Comment by marcofugaro** [comment]
Due altre regole fighe dai nostri amici di buildo
https://github.com/buildo/eslint-plugin-class-prefer-methods

**Comment by marcofugaro** [comment]
https://github.com/buildo/eslint-plugin-no-copy-paste-default-export

**Comment by caesarsol** [comment]
@marcofugaro per il secondo uso https://github.com/selaux/eslint-plugin-filenames :)

**Comment by marcofugaro** [comment]
All the previous rules have been reviewed and some implemented. Please open a new issue for new rules requests.
