### ISSUE TITLE
Generator star spacing rule

### ISSUE THREAD

**Issue by NoFishLikeIan** [accurat/accurapp#51]
We currently have a conflict between the rules in `eslint` and the formatting in `prettier`. In particular `eslint` forces to put a space before the generator `function * fetchOutsample()` and prettier defaults to `function* fetchOutsample()`. I like the prettier version more and would remove the eslint rule but I wanted to raise the issue to @marcofugaro first. For now you can do:
```
// .eslintrc
{
  "extends": "eslint-config-accurapp",
  "rules": {
    "generator-star-spacing": 0
  }
}

```

**Comment by marcofugaro** [comment]
`function* fetchOutsample()` is correct. This is also a conflict between prettier and eslint-config-standard, we should put this in the accurapp configuration, it resets it to the default:

```json 
'generator-star-spacing': 'warn',
```
