### ISSUE TITLE
Update README instructions about webhook policy

### ISSUE THREAD

**Issue by aminalhazwani** [accurat/accurapp#58]
@caesarsol [wrote](https://accurat.slack.com/archives/C07UZ4R0U/p1558344512001400) on Slack:

> ciao @devs, chi configura un deploy su Netlify, per piacere NON aggiunga un nuovo Slack Hook ma usi sempre questo:
https://accurat.slack.com/services/....
Hook: ...

So we need to change the instructions in the README accordingly 🙃

**Comment by marcofugaro** [comment]
Closed in 4803510c84bfcc84565850bf2468197c9f1ae9ec
