### ISSUE TITLE
Drop console messages in production

### ISSUE THREAD

**Issue by markov00** [accurat/accurapp#6]
What if we use `drop_console` option on uglifyjs to remove unwanted console logs in production?
https://github.com/mishoo/UglifyJS2#compressor-options

**Comment by marcofugaro** [comment]
già messo ;)

https://github.com/accurat/accurapp/blob/webpack-block-preset-accurapp/packages/webpack-blocks-preset-accurapp/index.js#L124

**Comment by markov00** [comment]
Ups, avevo visto questo:
https://github.com/accurat/accurapp/blob/webpack-block-preset-accurapp/packages/accurapp-scripts/config/webpack.config.prod.js

**Comment by marcofugaro** [comment]
hai ragione, il nuovo branch su cui stiamo lavorando è il [v3.0.0](https://github.com/accurat/accurapp/tree/v3.0.0)

ora cancello quel branch.
